### ISSUE TITLE
Convert the sample to NServiceBus 6

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/Webinar.SignalR#4]
I plan to use this sample in a user group presentation and I think at this stage NServiceBus 6 should be the preferred version.

@mauroservienti @SeanFeldman Thoughts?

**Comment by SeanFeldman** [comment]
Sounds good. Perhaps keeping a branch for v5 as well for a shirt time?

**Comment by MarcinHoppe** [comment]
Good idea, I'll create a support branch for V5 version.

**Comment by mauroservienti** [comment]
good idea 😄

**Comment by SeanFeldman** [comment]
Need a hand?

**Comment by MarcinHoppe** [comment]
I think it would be more fun as a group activity! I need to clear my TODO list a little bit first.

I'll comment on this issue when I start the update so you could chime in.

**Comment by MarcinHoppe** [comment]
@SeanFeldman Converted. Works on my machine but probably worth a double check.

**Comment by SeanFeldman** [comment]
Submitted 2 PRs (#5 and #6) with minor changes.

**Comment by MarcinHoppe** [comment]
Thanks @SeanFeldman. Merged to master and develop.
