### ISSUE TITLE
Update CSes to support deployment to Windows Server 2016

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/Webinar.SignalR#7]
> Visual Studio now supports deploying Cloud Services to OS Family 5 (Windows Server 2016) virtual machines. For existing cloud services, you can change your settings to target the new OS Family. When creating new cloud services, if you choose to create the service using .net 4.6 or higher, it will default the service to use OS Family 5.

Guest OS family code is here https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-guestos-update-matrix#family-5-releases

**Comment by MarcinHoppe** [comment]
Forgive my ignorance, but does this matter when running under the emulator?

**Comment by SeanFeldman** [comment]
It doesn't. When someone is trying to deploy it does.
It's also a good practice to roll with the latest OS family as older ones get deprecated.

**Comment by MarcinHoppe** [comment]
OK, got it. Is there anything to change in the code then to allow for using Windows Server 2016? In all my Azure noobness, I can't see anything that pertains to the guest OS in the CS config. Should we bump the targeted .NET Framework version?

**Comment by SeanFeldman** [comment]
Nothing in code. PR #8 pending.

**Comment by MarcinHoppe** [comment]
Sorry, I haven't seen the PR. LGTM, merging.

**Comment by SeanFeldman** [comment]
Don't be. I was lazy to send a PR and opened an issue first. PR was created seconds ago 😊
